// <auto-generated />
using System;
using ASP.NET_Core_MVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP.NET_Core_MVC.Migrations
{
    [DbContext(typeof(TermContext))]
    [Migration("20220711213146_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASP.NET_Core_MVC.Models.Term", b =>
                {
                    b.Property<int>("TermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Page")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Stage")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TermId");

                    b.ToTable("Terms");

                    b.HasData(
                        new
                        {
                            TermId = 4,
                            Page = 33,
                            Stage = 1,
                            TermName = "web app"
                        },
                        new
                        {
                            TermId = 3,
                            Page = 33,
                            Stage = 1,
                            TermName = "local area network (LAN)"
                        },
                        new
                        {
                            TermId = 2,
                            Page = 33,
                            Stage = 1,
                            TermName = "URL (Uniform Resource Locator)"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
