// <auto-generated />
using System;
using ASP.NET_Core_MVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP.NET_Core_MVC.Migrations
{
    [DbContext(typeof(TermContext))]
    partial class TermContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASP.NET_Core_MVC.Models.Chapter", b =>
                {
                    b.Property<string>("ChapterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChapterId");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            ChapterId = "I",
                            Name = "Introduction"
                        },
                        new
                        {
                            ChapterId = "s",
                            Name = "single"
                        },
                        new
                        {
                            ChapterId = "B",
                            Name = "Bootstrap"
                        },
                        new
                        {
                            ChapterId = "d",
                            Name = "data-driven"
                        },
                        new
                        {
                            ChapterId = "t",
                            Name = "testing"
                        },
                        new
                        {
                            ChapterId = "c",
                            Name = "controllers"
                        },
                        new
                        {
                            ChapterId = "R",
                            Name = "Razor"
                        });
                });

            modelBuilder.Entity("ASP.NET_Core_MVC.Models.Term", b =>
                {
                    b.Property<int>("TermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChapterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Page")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Stage")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TermId");

                    b.HasIndex("ChapterId");

                    b.ToTable("Terms");

                    b.HasData(
                        new
                        {
                            TermId = 4,
                            ChapterId = "R",
                            Page = 33,
                            Stage = 1,
                            TermName = "web app"
                        },
                        new
                        {
                            TermId = 3,
                            ChapterId = "c",
                            Page = 33,
                            Stage = 1,
                            TermName = "local area network (LAN)"
                        },
                        new
                        {
                            TermId = 2,
                            ChapterId = "t",
                            Page = 33,
                            Stage = 1,
                            TermName = "URL (Uniform Resource Locator)"
                        });
                });

            modelBuilder.Entity("ASP.NET_Core_MVC.Models.Term", b =>
                {
                    b.HasOne("ASP.NET_Core_MVC.Models.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
